### PR TITLE
Added hardcoded support for tilting Fisheye center of view. ToDo: add…

### PR DESCRIPTION
**Pull request by vitos1k**
… camera parameters for tilting in the interface

### CODE REVIEW

**Comment by vitos1k** [comment]
I assume similar tilting is happening in the Equirectangular camera section, and tilting is hardocoded there too,  we could utilize the same parameters for two cameras. And user would adjust center of interest by himself

**Comment by bezo97** [comment]
This looks surprisingly simple! Are you able to verify that this works correctly? Unfortunately I don't have access to a dome projector.

Another question I'm not sure about is whether we should crop out the parts of the circle [like shown here](https://paulbourke.net/dome/fishtilt/). I managed to make it work but it requires some of the changes I've done on the `dev` branch earlier. If it's fine I'll add this too after merge. 
image

**Comment by vitos1k** [comment]
> This looks surprisingly simple! Are you able to verify that this works correctly? Unfortunately I don't have access to a dome projector.
> 
> Another question I'm not sure about is whether we should crop out the parts of the circle [like shown here](https://paulbourke.net/dome/fishtilt/). I managed to make it work but it requires some of the changes I've done on the `dev` branch earlier. If it's fine I'll add this too after merge. image

It is simple. And yes it works correctly, I can verify.

There is no need to crop. Usually fisheye master images are square with fisheye circle fit perfectly in center

**Review by bezo97 — APPROVED** [review]
Thanks for the contribution, I'll add gui controls for it soon

**Pull request merged**
